### ISSUE TITLE
RUN on Windows System

### ISSUE THREAD

**Issue by laichao2018** [ZhipengCai/Demo---Practical-optimal-registration-of-terrestrial-LiDAR-scan-pairs#2]
Thank you for your wonderful works! My computer is run on Windows System, but it seems your test was based on Linux, May it running on Windows? And what do I need to prepared? 
Look forward for your response!

**Comment by ZhipengCai** [comment]
> Thank you for your wonderful works! My computer is run on Windows System, but it seems your test was based on Linux, May it running on Windows? And what do I need to prepared?
> Look forward for your response!

Thanks for being interested in this work.

I would expect it to also compile normally on windows, but not 100% sure. The thing you need to do is the same as described in Readme. In the worst case, I think you only minor modifications on the code are required to remove the dependency on Linux.
